### ISSUE TITLE
Please update files on Anki add-on page

### ISSUE THREAD

**Issue by vijjo** [yu7777/Control-Audio-Playback-Speed#2]
This is not an issue with the plugin. 
I'd just like to tell you that your plugin on [the Anki add-on page](https://ankiweb.net/shared/info/1067025219) hasn't been up-to-date with the one on Github. Hence, when I installed the add-on to Anki through its downloading code `1067025219`, I didn't get the latest version. It took me a while to figure out why `Backspace` didn't work on mac. 
The add-on version on Github works fine though.
Please update on the Anki add-on page, so that people can use the wonderful plugin!
Thank you for the handy add-on!

**Comment by yu7777** [comment]
Actually I am not using this add-on anymore. Nevertheless, I have already updated this add-on on Anki add-on page.

**Comment by vijjo** [comment]
Thank you very much!
